version: '{branch}-{build}'

branches:
  only:
    - master

image:
  - Visual Studio 2019
  - macos
  - Ubuntu2004

configuration:
  - release

for:
-
  matrix:
    only:
      - image: macos

  install:
    - 'export HOMEBREW_NO_AUTO_UPDATE=1'
    - brew install poppler

  build_script:
    - 'export QTDIR="$HOME/Qt/5.15/clang_64"'
    - 'export PATH="$QTDIR/bin:$PATH"'
    - qmake -v
    - qmake -r
    - make

  after_build:
    - '(chmod +x deploy-osx.sh && ./deploy-osx.sh && mv tikzit.dmg tikzit-osx.dmg)'
    - python scripts/gh-push.py tikzit-osx.dmg
-
  matrix:
    only:
      - image: Ubuntu2004

  install:
    - sudo apt-get update
    - sudo apt-get -y install flex bison libpoppler-cpp-dev libgl-dev

  build_script:
    - 'export QTDIR="$HOME/Qt/5.15/gcc_64"'
    - 'export PATH="$QTDIR/bin:$PATH"'
    - qmake -v
    - qmake
    - make

  after_build:
    - ./deploy-linux.sh
    - mv dist/tikzit.tar.gz tikzit-linux.tar.gz
    - python scripts/gh-push.py tikzit-linux.tar.gz
-
  matrix:
    only:
      - image: Visual Studio 2019

  install:
    - choco install winflexbison
    - choco install poppler
    - 'C:\Qt\5.15\msvc2019\bin\qtenv2.bat'
    - cd C:\projects\tikzit

  before_build:
    # - ps: (new-object net.webclient).DownloadFile('http://tikzit.github.io/download/win32-deps.zip', 'c:\projects\tikzit\win32-deps.zip')
    - ps: (new-object net.webclient).DownloadFile('https://github.com/oschwartz10612/poppler-windows/releases/download/v21.11.0-0/Release-21.11.0-0.zip', 'c:\projects\tikzit\poppler.zip')
    - 7z x poppler.zip

  build_script:
    - 'call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars32.bat"'
    - qmake -v
    - qmake
    - nmake
    # - mingw32-make

  after_build:
    - deploy-win.bat
    - move dist\tikzit.zip tikzit-win.zip
    - python scripts\gh-push.py tikzit-win.zip


